url for form data: https://docs.google.com/forms/d/e/1FAIpQLSeitoyUkcXqKklQOIzY9JLlVV4u9HdRHyT_pc7y0Ug6jVxTfA/alreadyresponded


In [11]:
import os
import numpy as np
import matplotlib.pylab as plt
from PIL import Image

In [12]:
mainpath = "jpgs"
array = np.zeros([20, 512, 512, 3])
re_img = []

In [13]:
for dirName, subdirList, fileList in os.walk(mainpath):
    print('Found directory: %s' % dirName)   
    for photoid in fileList:
        print('file name: \t%s' % photoid)
        print('Found directory: %s' % dirName)
        #i = plt.imread(fname)
        i = Image.open(dirName+"/"+photoid)
        resize = i.resize((512,512))
        np_re_img = np.array(resize)
        re_img.append(np_re_img)

Found directory: jpgs
file name: 	cat-iphone-wallpaper-1.jpg
Found directory: jpgs
file name: 	cat-iphone-wallpaper-10.jpg
Found directory: jpgs
file name: 	cat-iphone-wallpaper-11.jpg
Found directory: jpgs
file name: 	cat-iphone-wallpaper-12.jpg
Found directory: jpgs
file name: 	cat-iphone-wallpaper-13.jpg
Found directory: jpgs
file name: 	cat-iphone-wallpaper-14.jpg
Found directory: jpgs
file name: 	cat-iphone-wallpaper-15.jpg
Found directory: jpgs
file name: 	cat-iphone-wallpaper-16.jpg
Found directory: jpgs
file name: 	cat-iphone-wallpaper-17.jpg
Found directory: jpgs
file name: 	cat-iphone-wallpaper-18.jpg
Found directory: jpgs
file name: 	cat-iphone-wallpaper-19.jpg
Found directory: jpgs
file name: 	cat-iphone-wallpaper-2.jpg
Found directory: jpgs
file name: 	cat-iphone-wallpaper-20.jpg
Found directory: jpgs
file name: 	cat-iphone-wallpaper-21.jpg
Found directory: jpgs
file name: 	cat-iphone-wallpaper-22.jpg
Found directory: jpgs
file name: 	cat-iphone-wallpaper-3.jpg
Found direc

In [14]:
array = np.array(re_img)

In [15]:
print (array)
print (f"Array shape: {array.shape}")

[[[[224  77  85]
   [225  78  86]
   [225  78  86]
   ...
   [240  99 107]
   [241 100 108]
   [240  99 107]]

  [[221  74  82]
   [225  78  86]
   [225  78  86]
   ...
   [240  99 107]
   [240  99 107]
   [240  99 107]]

  [[224  77  85]
   [223  76  84]
   [223  76  84]
   ...
   [238  97 105]
   [239  98 106]
   [238  97 105]]

  ...

  [[252 125 134]
   [252 125 134]
   [253 123 133]
   ...
   [146  24  35]
   [146  24  35]
   [146  24  35]]

  [[254 122 133]
   [255 123 134]
   [255 123 134]
   ...
   [146  24  35]
   [146  24  35]
   [144  22  33]]

  [[254 122 133]
   [255 123 134]
   [255 123 134]
   ...
   [146  24  35]
   [145  23  34]
   [143  21  32]]]


 [[[197 199 212]
   [197 199 212]
   [198 200 213]
   ...
   [196 198 211]
   [196 198 211]
   [196 198 211]]

  [[197 199 212]
   [197 199 212]
   [198 200 213]
   ...
   [196 198 211]
   [196 198 211]
   [196 198 211]]

  [[197 199 212]
   [197 199 212]
   [198 200 213]
   ...
   [197 199 212]
   [197 199 212]
   [197 199